services:
  wiremock:
    image: wiremock/wiremock:3.0.0-1
    ports:
      - "9090:8080"
    volumes:
      - ./config/wiremock:/home/wiremock
    command:
      - --verbose
      - --global-response-templating
    restart: unless-stopped

  api-service-notifier:
    depends_on:
      wiremock:
        condition: service_started
    env_file: config/backend/mock-notifier.env
    ports:
      - "8080:8080"

  api-service-sms-sender:
    depends_on:
      wiremock:
        condition: service_started
    env_file: config/backend/mock-smssender.env

#  api-service-teams-sender:
#    environment:
#      SPRING_PROFILES_ACTIVE: mock
#      GRAPH_BASE_URL: http://wiremock:8080
#    env_file: config/backend/mock-teams-sender.env

  csv-filereader:
    environment:
      SPRING_PROFILES_ACTIVE: mock
    env_file: config/backend/mock-csv-filereader.env
    volumes:
      - ./config/backend/application-csv-filereader.yml:/app/config/application.yml
      - ./config/mock-data/OrgExport.csv:/data/temp/OrgExport.csv
      - ./config/mock-data/EmpExport.csv:/data/temp/EmpExport.csv
      - csv_incoming:/data/incoming
      - csv_processed:/data/processed
      - csv_failed:/data/failed
      - csv_temp:/data/temp

  api-service-webappusers:
    env_file: config/backend/mock-webappusers.env

  web-app-nidhogg:
    depends_on:
      wiremock:
        condition: service_started

  db:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/db/db-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - db_data_mock:/var/lib/mysql

volumes:
  db_data_mock:
  csv_incoming:
  csv_processed:
  csv_failed:
  csv_temp: